---
title: 消除宫颈癌计划-中国还有很长的路
subtitle: 认识HPV疫苗
date: "2023-03-04"
slug: hpvday
categories: [科普]
keywords: [宫颈癌,科普,HPV]
toc: true
draft: true
---


## 全球宫颈癌消除计划

全球宫颈癌消除计划（Global Cervical Cancer Elimination Initiative，简称CCCI）是由世界卫生组织（WHO）和国际癌症研究机构（IARC）于2018年联合发起的一个全球性项目，旨在推动全球范围内宫颈癌的消除工作，实现2030年前宫颈癌发病率和死亡率的显著降低。

该计划制定了以下目标，从而促进全球范围内宫颈癌防治工作的整体推进。

- 推广宫颈癌的疫苗接种；
- 加强宫颈癌的早期筛查和诊断；
- 提高宫颈癌的治疗和管理水平；
- 通过政策、财务和社会环境等多个方面的综合干预。

同时，也提出了2030年的阶段目标

- 90%女孩在15岁之前全程接种HPV疫苗；
- 70%妇女在35岁-45岁接受高效能的宫颈癌筛查；
- 90%确诊子宫颈疾病的妇女得到规范治疗。

中国于2018年宣布加入“全球消除宫颈癌计划”，这对于推动中国宫颈癌的防治工作，提高全民的宫颈癌认识和防范意识，具有重要的意义。

## 中国宫颈癌的疾病负担

中国女性宫颈癌的疾病负担较重，中国肿瘤登记数据显示，2016年宫颈癌粗发病率和粗死亡率分别为17.69/10万和5.52/10万，其标化率分别为11.34/10万和3.36/10万。中国宫颈癌的发病率和死亡率在全球不同国家和地区之中处于中等偏下，略低于全球平均的宫颈癌的发病率和死亡率分（13.3/10万和7.3/10万）以及非洲、南美和南亚地区，而高于欧洲，北美及西亚等地区。

虽然中国宫颈癌的发病率和死亡率处于全球平均水平偏下，但是每年的新发宫颈癌发病例数和死亡病例数分别达到了11.93万例和3.72万例，占全球宫颈癌发病和死亡病例数的19.75%和10.88%。

在中国的不同地区之间，宫颈癌发病率呈现农村高于城市，中西部地区高于东部地区的特点。

中国在承受宫颈癌较高的疾病负担的同时，其发病率和死亡率也呈现明显的上升趋势，在2000年至2016年期间，宫颈癌发病率以平均每年8.5%和5.4%的速度上升。

## 目前存在问题

HPV疫苗确实能阻断HPV的感染，而效果

