project:
  type: website
  resources:
    - "*.pdf"
    - baidu_verify_code-aDCTvXezZP.html
    - /report/2021/
    - /fonts/
    - author.png
    - /qsight/qsightpic.jpeg
    - /slides/2023-5-16-canreg-report/example.html
    - /training/annumeeting2023/images/

website:
  title: "普癌新声"
  description: "一个公共卫生医师的个人网站"
  favicon: favicon.png
  twitter-card: true
  open-graph: true
  site-url: https://www.chenq.site


  navbar:
    background: "primary"
    search: true
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: tropical-storm
        href: /qsight/
        text: Qsight博客
      - icon: pen
        href: https://diary.chenq.site
        text: 随笔录
      - icon: hexagon
        href: https://canregtools.chenq.site
        text: Packages
      - icon: journal-medical
        href: /publications/
        text: 出版作品
      - icon: file-slides-fill
        href: https://slides.chenq.site
        text: Slides
      - href: about.qmd
        text: 关于
    right:
      - icon: rss
        href: /qsight/index.xml
        aria-label: RSS
      - icon: pen
        href: https://notes.chenq.site
        text: 学习笔记

  page-footer:
    border: true
    left: "Copyright@Qiong Chen"
    center: "豫ICP备2021032022号"
    right:
      - icon: github
        href: https://github.com/gigu003
        aria-label: Qiong@GitHub
      - icon: rss
        href: /qsight/index.xml
        aria-label: RSS     
freeze: auto  

format:
  html:
    code-line-numbers: true
    toc: false
    theme: flatly
    css: styles.css
    include-in-header: baidusta.html
