project:
  type: website
  preview:
    port: 5050
  resources:
    - "*.pdf"
    - /report/2021/
    - /fonts/
    - /qsight/assets/images/*
    - /slides/2023-5-16-canreg-report/example.html
    - /training/annumeeting2023/images/
    - /packages/canregtools/versions/

website:
  title: "普癌新声"
  description: "一个公共卫生医师的个人网站"
  favicon: favicon.png
  twitter-card: true
  open-graph: true
  site-url: https://www.chenq.site
  page-navigation: true
  back-to-top-navigation: true
  google-analytics:
    tracking-id: "GTM-NPK7BT6Z"
    anonymize-ip: true
  navbar:
    background: "primary"
    search: true
    left:
      - icon: house
        href: index.qmd
        text: Home
      - icon: tropical-storm
        href: qsight.qmd
        text: Qsight博客
      - icon: pen
        href: https://diary.chenq.site
        text: 随笔录
      - icon: hexagon
        href: /packages/
        text: 软件
      - icon: journal-medical
        href: /publications/
        text: 出版作品
      - icon: file-slides-fill
        href: https://slides.chenq.site
        text: Slides
      - href: about.qmd
        text: 关于
    right:
      - icon: rss
        href: /qsight/index.xml
        aria-label: RSS
      - icon: pen
        href: https://notes.chenq.site
        text: 学习笔记
  page-footer:
    border: true
    left: "Copyright@ 2025 Qiong Chen"
    center: "豫ICP备2021032022号"
    right:
      - icon: github
        href: https://github.com/gigu003
        aria-label: Qiong@GitHub
      - icon: rss
        href: /qsight/index.xml
        aria-label: RSS
freeze: auto

format:
  html:
    code-line-numbers: true
    toc: false
    theme: flatly
    css:
      - _assets/css/qsight.css
    margin-header: _assets/sidebar-wechat.html
