---
title: "肿瘤临床预后影响因素分析应该注意哪些因素?"
description: |
  今天我审读了一篇肿瘤临床预后影响因素分析的投稿论文，也想起了以前看过的几篇临床肿瘤预后影响因素的文章，我发现他们在进行数据分析的时候存在某些共同的问题，今天在这里和大家分享一下我的一些观点，希望能对肿瘤预后分析的朋友有所帮助。
categories: 
  - 数据分析
keywords:
  - 肿瘤预后分析
date: 2023-03-21
draft: false
---

:::{.callout-tip collapse="true" }
## 肿瘤预后影响因素分析，下面这些问题你考虑过吗？
 - 怎样才能确定因素是否为预后独立影响因素？
 - 如何筛选潜在的混杂因素？
 - 如何判断模型拟合效果？
 - 需要使用哪个统计模型？
 - 结果数据该如何展现？
:::

今天我所审读的这篇论文题目是“淋巴瘤临床流行病学特点及利妥昔单抗和BTK抑制剂应用对预后影响”的文章，由于该文章正处于投稿阶段，不能把文章展示出来，但是这篇文章存在的一些问题是目前肿瘤预后分析时一些常见的问题，也是一些共性的问题，今天在这里分享一下我的一些观点和看法，如果刚好你也在进行相关的研究或者数据分析，不妨停下来看一看，说不定对你有所帮助。

临床上肿瘤预后影响因素分析的文章有很多，大多为分析治疗因素对预后的影响，预后的指标多为总体生存和无进展生存。我看过一些临床的论文，得出的最后结论提示某某因素是某癌症预后的**独立**影响因素，那你有没有想过什么是独立的预后影响因素？达到什么样的条件才能成为独立的预后影响因素？

我们先把这个问题放到一边，先从临床的角度想一想，癌症的预后可能与哪些因素有关系？除了治疗因素之外，癌症诊断时的临床分期、病理类型、患者的基础状态以及其他的一些流行病学因素可能均与癌症的预后有关系，这些因素可能在一定程度上影响着患者的总体生存（OS）或者无进展生存（PFS），但是它们对预后影响的效应可能大小不一。

当我们把焦点聚焦到某一个因素上时，比如治疗因素时，我们想通过收集的数据分析一下治疗因素对预后影响的效应大小，那么我们就需要把其他可能影响因素效应排除在外，即把治疗因素以外因素的效应调整之后，才能显示出来治疗因素对预后影响的真实效应。

那从流行病学的角度来讲的话，上面所说的过程就是**去除混杂因素**的过程，简单的说，所研究因素之外，可能对研究结局产生影响的因素就是混杂因素。那在实际数据分析的过程中，怎么判断哪些因素是混杂因素需要调整，而哪些因素不是混杂因素而不需要调整呢？

我觉得可以从两个方面来判断，首先是从专业方面，我们可以通过阅读文献来了解目前证据所支持的所研究结局的影响因素有哪些？这些可能都是**潜在**的混杂因素。我们知道了这些因素之后，在数据收集阶段应该尽可能的把这些因素收集上来，以备后面的分析来用；第二个方面，就是利用自己研究所收集的数据来探索分析，通常按照*研究因素分层*来看其他不同的因素在不同层间是否分布均衡，如果不均衡的话，那么就需要这些层间不均衡分布的因素，也列入潜在的混杂因素清单，需要纳入调整模型进行校正。

那我们再从统计的角度来说，临床上常用的预后影响因素分析的统计学方法为Cox比例风险回归模型。这个阶段已经数据分析的最后阶段了，我们把所研究因素（治疗方法）作为自变量，把潜在的混杂因素作为协变量，把结局因素（生存状态，生存时间）作为因变量纳入Cox比例风险回归模型进行模型的拟合。调整了协变量的影响之后，研究因素与结局之间的关系，通常用HR来表示，才是真正的研究因素对研究结局的效应大小。

当然在这一步骤里，有人会问：“所有这些潜在的混杂因素最终都要放入模型吗，有没有一些潜在的混杂因素会剔除出模型？”

答案是会的，有一些潜在混杂因素会剔除出模型，主要还是要看模型拟合的情况。如果研究样本量不大，而潜在的混杂因素又很多的时候，我们就需要评估纳入哪些变量以使模型的拟合效果更好(R^2)。或者通过把这个变量纳入和剔除模型前后对研究因素对结局变量效应值的影响大小来判断，如果变化超过10%，那么我们可以考虑纳入模型，反之则剔除出模型。

现在再回到前面第二段的问题，什么样的因素才是癌症预后独立的影响因素呢？

如果你认真看完了上面的几段，我想答案应该显而易见了，所谓癌症预后的独立影响因素应该是排除了研究因素与研究结局之间除了研究因素以外的所有干扰因素之后，研究因素仍然对结局有影响，那么我们可以成为这个研究因素是结局的独立影响因素。

以上的过程是我所理解的肿瘤临床预后影响因素分析的大概过程，这个过程虽然听起来挺简单的，但是总会有各种各样的问题出现。比如统计方法的使用是否合适、该展示的数据没有展示出来等等。

数据分析完成之后，我们就需要以论文或者报告的形式把分析的结果展示出来。我们都知道任何一项研究都不可能做到非常完美，但是我们所能做的就是尽可能得调整混杂因素，去伪存真，展示真实的结局。

在论文撰写的时候，我们要向读者展示出来，所有可能影响结果的地方，我都已经考虑了，而且进行了调整，而有些内容确实没有办法做，我们可以把它列入研究存在的不足和限制方面。如果能做到这一点，我相信你的论文应该是一篇质量很高的论文，还愁发表吗？

这就是我对临床肿瘤预后分析的一点理解，如果你有不同的见解请告诉我，将不胜感激！





