---
title: 肿瘤登记质量控制的四类指标
author: 陈琼
date: '2022-03-10'
slug: qualitycontrol
link: https://chenq.site/tech/2022-qualitycontrol/
categories: [肿瘤登记]
tags:
  - 肿瘤登记质量控制
canreg: 技术文档
feature: no
keywords:
  - 肿瘤登记
  - 质量控制
  - 可比性
  - 完整性
  - 有效性
  - 时效性
summary: ''
---

肿瘤登记工作的宗旨就是为覆盖地区提供全部恶性肿瘤发病、死亡、生存等信息，描述恶性肿瘤疾病负担，从而为肿瘤防控政策的制定、恶性肿瘤流行病学研究以及防控效果评估提供信息。

质量控制在实现上述肿瘤登记工作宗旨中至关重要，因为不可靠的数据将会为肿瘤防控政策制定、科学研究等提供错误的方向，从而影响肿瘤防控效果。

目前我国肿瘤登记在评估数据质量方面主要采用可比性、完整性、有效性和时效性四类指标。

## 可比性

肿瘤登记资料的可比性是指不同肿瘤登记处之间恶性肿瘤发病率、死亡率、生存率等是真实可比的，不同登记处之间率的不同是由于数据本身不同而产生，不是因为标准或质量不同而产生。

可比性的一个基础先决条件是不同登记处采用一套通用的标准或定义，同时，可比性也是登记处执行国际标准化的编码、分类和记录以及报告项目定义的程度。

常用的可比性指标有：发病的定义、偶发病例的诊断、分类与编码、多原发肿瘤标准、死亡数据等

## 完整性

肿瘤登记资料的完整性是指在登记处覆盖地区目标人群中*发现*的肿瘤发病病例与本地区现实世界所有的肿瘤发病病例的符合程度。即登记处数据库中包含目标人群内发生肿瘤病例数的程度（以百分数表示）。

完整性是肿瘤登记数据的重要属性。

在实际中，没有一个登记处的数据完整性能够达到理想的100%，我们登记处所需要做的就是使完整性尽量接近100%，以达到完整性的最大化。

完整性达到最大化时，所计算的肿瘤发病率、死亡率等指标与登记处覆盖地区目标人群肿瘤发病率、死亡率的**真实值**最接近。

因此，完整性是肿瘤登记质量控制过程中的重要部分，完整性的评价标准有：

- 一定时间内稳定的发病率
- 不同地区人群可比较的发病率
- 年龄别发病率曲线
- 儿童肿瘤的发病率
- 组织学诊断确认的比例（MV%）
- 死亡发病比（M:I）
- 死亡医学证明确认的比例。


## 有效性

有效性是评价肿瘤登记质量的一个基本内容，是指登记病例中具有给定特征（比如，肿瘤部位、年龄、性别、诊断、编码）的真正属性的病例所占的比例。

常用的指标：MV%、DCO%、原发部位不详或未特指的病例所占的百分比（other and unspecified, O&U%）,年龄不明的百分比等。


## 时效性

肿瘤登记资料的时效性是肿瘤登记处收集、处理、报告足够可靠和完整的肿瘤资料的*及时性*。常常需要平衡*及时报告*和获取*完整、准确的肿瘤信息*的关系。病例发生后，各级登记机构要及时向上报告。医疗机构应在患者出院后1周内收集病例信息并在规定时间内上报。在每年的年末发现的病例，更要及时收集、登记、报告。未能及时报告的病例可能影响到年度分析报告--相当于漏报。



