---
title: MAC OS 中使用ggplot2作图无法显示中文
date: "2023-02-20"
slug: default-language-R
categories: [作图,R语言,MAC OS]
keywords: [R语言,MACOS]
draft: true
---

当你在MAC OS是使用ggplot2作图时，可能会遇到无法显示中文的问题，有中文的地方均显示为一个方框，这个让人多少有点难受。下面我们就整理一下解决此问题的方法，并汇总如下。

## 使用showtext包加载中文字体

首先，安装showtext包

```{r}
#| eval: false
install.packages("showtext")
```

加载showtext包，并显示当前环境中可用的字体

```{r}
library(showtext)
# 使用font_families()函数查看当前环境中可供使用的字体
font_families()
```

Google上有很多可以用的免费字体，showtext可以加载google字体

```{r}
#| eval: false
font_add_google("Noto Serif Simplified Chinese")
```

下面我们可以再次查看一下当前环境中的字体有哪些，我们就可以使用加载的中文字体来作图了。
```{r}
## 自动使用showtext渲染字体
showtext_auto()
#现在再看看目前环境中的可用字体有哪些
font_families()
```

```{r}
hist(rnorm(1000), breaks = 30, col = "steelblue", border = "white",
     main = "随机数直方图", xlab = "", ylab = "Frequency")
showtext_begin()
text(2, 70, "例数:1000", family = "wqy-microhei", cex = 1.5)
showtext_end()
```


打开Mac OS的terminal终端，输入如下命令


```terminal
locale
export LANG=en_US.UTF-8
export LANG=en_US.UTF-8
```

