---
title: 制作《2021河南省肿瘤登记年报》科普视频
author: 陈琼
date: '2022-04-10'
slug: report-video
link: https://chenq.site/tech/2022-report-video/
categories:
  - 肿瘤登记
  - 肿瘤登记年报
keywords:
  - 肿瘤登记
  - 肿瘤登记年报
  - 年报科普视频脚本
---

《2021河南省肿瘤登记年报》的发布为河南省癌症的防控工作提供了数据参考，对防控相关专业人员参考癌症负担数据具有重要意义。同时，为了使普通大众了解河南省癌症的发病死亡情况，我们将制作科普视频，相关工作整理记录如下。

## 科普视频知识点

- 河南省癌症中心/河南省肿瘤医院发布《2021河南省肿瘤登记年报》；
- 河南省居民癌症发病率为272.33/10万，死亡率为162.16/10万；河南省每年新诊断恶性肿瘤28.6万例，因恶性肿瘤死亡16.8万例；
- 癌症发病和死亡的人群分布均以老年人为主，河南省癌症年龄发病率自40~岁组开始快速上升，在85岁组达到峰值，65岁以上诊断患者和死亡患者占全部发病和死亡患者的47.3%和65.3%；
- 男性和女性发病谱存在差异，男性发病率和死亡率均高于女性，男女发病比为1.05，男女死亡比为1.51; 男性和女性高发癌种存在差异，男性发病前五位癌症分别为肺癌、胃癌、食管癌、肝癌和结直肠癌，而女性前五位癌种分别为乳腺癌、肺癌、食管癌、宫颈癌和胃癌；不管是男性还是女性，肺癌均位居癌症死因的首位，其次为胃癌、食管癌、肝癌和乳腺癌。
- 河南居民癌症发病和死亡也存在地区差异，城市地区癌症发病率高于农村地区，而死亡率低于农村地区，常见癌种分布也存在一定差异，河南省北部太行山脉地区是食管癌和胃癌的高发地区，城市地区则肺癌、结直肠癌、甲状腺癌相对高发。

## 科普视频脚本

大家好，癌症是威胁居民健康和生命的主要问题，河南省癌症中心/河南省肿瘤医院在2022年肿瘤防治宣传周期间发布了《2021河南省肿瘤登记年报》，对河南省居民的癌症发病和死亡情况进行了详细介绍，下面跟随小编一块来了解一下吧。

《年报》显示，2018年河南省癌症发病率为272.33/10万，每小时约有32例患者被诊断，共诊断28.6万例；癌症死亡率为162.16/10万，每小时约19例癌症患者死亡，共死亡16.8万例。

河南省癌症的发病率和死亡率呈现如下变化特点：

### 癌症患者以**老年人**为主

发病率和死亡率均随着年龄的增加而上升，在39岁之前处于相对降低且平稳的状态，而40岁之后则快速上升，在85岁年龄组达到峰值。癌症患者以老年人为主，新诊断患者中，65岁以上者占47.3%；死亡患者中，65岁以上者占65.3%。

### 癌症患者存在**性别差异**
男性发病率和死亡率均高于女性，男女性别比分别为1.05和1.51。

男性和女性的**发病谱**也有所不同，男性前5位癌种分别为肺癌、胃癌、食管癌、肝癌和结直肠癌；女性前5位癌种乳腺癌、肺癌、食管癌、宫颈癌和胃癌。

### 癌症发病率和死亡呈现**地区差异**
城市地区癌症发病率高于农村地区，而死亡率则呈现农村高于城市的特点。

在癌种的地区分布方面，结直肠癌和甲状腺癌在城市地区的顺位比农村地区靠前，食管癌和胃癌则在河南省北部的太行山脉地区和西部的伏牛山地区相对高发。

癌症防治需要我们每一个人参与，生活中我们注意避开常见的癌症危险因素，注意定期体检，你我携手，共抗癌症吧！

扫描二维码，了解更加详细的《年报》内容吧。


## 科普视频成片分享

马上上线

