---
title: 中国肿瘤登记管理办法
author: 陈琼
date: '2022-03-18'
slug: file
link: https://chenq.site/tech/2022-file/
categories: [肿瘤登记]
keywords:
  - 肿瘤登记
  - 中国肿瘤登记管理办法
---

## 起草背景
肿瘤登记是系统性、经常性收集有关肿瘤及肿瘤病人信息的统计制度，是癌症防治工作的基础。为掌握我国癌症发病、死亡情况，2008年，中央财政支持开展肿瘤登记项目工作，项目覆盖面和覆盖人群不断扩大，到2014年全国肿瘤登记点已达308个，覆盖全国约3亿人。肿瘤登记项目工作为建立统一、规范的肿瘤登记报告制度与方法，动态收集我国恶性肿瘤的相关信息，奠定了坚实的基础。

随着城镇化、老龄化、工业化、全球化快速发展，癌症等慢性病疾病负担日趋加重，肿瘤登记工作面临一些新情况、新问题。为了进一步加强全国肿瘤登记工作规范化管理，获得及时、统一、准确的肿瘤发病、死亡和生存信息，使肿瘤登记工作满足当前癌症防治工作需要，国家卫生计生委和国家中医药管理局组织有关专家，在广泛征求各方面意见的基础上，制定了《肿瘤登记管理办法》。


## 主要内容
《管理办法》包括总则、组织机构和职责、肿瘤登记内容和工作流程、质量控制与考核评价、保障措施、附则，共六章二十条。主要内容如下：

### 肿瘤登记的目的和意义以及适用范围。
为建立常规报告制度，加强肿瘤随访登记工作规范化管理，健全我国以人群为基础的肿瘤随访登记信息系统，掌握我国城乡居民恶性肿瘤发病、死亡、生存情况及变化趋势，科学评价癌症防控效果,及时调整癌症防治策略，为我国肿瘤防治工作提供必要的信息。本办法适用于卫生计生行政部门、中医药管理部门、医疗卫生机构和疾病预防控制机构开展的肿瘤登记管理工作。

### 各级组织机构和职责。
各级卫生计生行政部门和中医药管理部门负责全国肿瘤登记体系建设、组织协调和监督管理全国肿瘤登记工作。国家癌症中心负责全国肿瘤登记工作的具体工作，包括制定全国肿瘤登记工作计划、实施方案、质量控制和评价标准，建立全国肿瘤登记信息系统和跨区域肿瘤登记病例数据交换制度，组织开展技术培训、督导检查和考核评估，负责肿瘤登记信息的数据收集、质量控制和统计分析等。各省（直辖市、自治区）卫生计生行政部门和中医药管理部门指定相关部门成立省级肿瘤登记中心，实施全省肿瘤登记工作。省会城市、地级市为城市肿瘤登记地区，指定相关部门设立肿瘤登记处，开展市辖区的肿瘤登记报告工作；县级市和县为农村肿瘤登记地区，指定相关部门设立肿瘤登记处，开展辖区内肿瘤登记报告工作。登记处所在的疾病预防控制中心负责提供死因数据。

### 登记内容和工作流程。
肿瘤登记处辖区内所有医疗机构需定期向肿瘤登记处报告所有恶性肿瘤（包括中枢神经系统良性肿瘤）病例的发病和死亡信息。肿瘤登记处对辖区工作进行指导、检查及培训、数据收集和质量控制工作并定期开展病例随访，按时将数据和工作总结上报省级肿瘤登记中心。省级肿瘤登记中心开展全省肿瘤登记报告资料的收集汇总、质量控制和统计分析，按时将数据和工作总结上报国家癌症中心。国家癌症中心定期汇总和分析登记资料、编制各种报表，形成年度肿瘤登记报告，按时上报国家卫生和计划生育委员会审核后发布。

### 质量控制、考核评价和保障措施。
国家癌症中心建立和实施评价机制，制订实施监测指标体系。明确各级登记系统的管理部门组织实施督导检查和考核评价。要求各级卫生计生行政部门和中医药管理部门加强组织领导和协调，建立目标责任制，实行绩效管理，提供政策、人员和经费保障，全面推进肿瘤登记工作实施。与公安、民政、统计等相关部门建立工作联系。加强人才培养，提高工作能力。保障信息安全，遵从国家法律、知识产权和伦理学准则，保证患者隐私。

## 文件下载
[中国肿瘤登记管理办法，国卫疾控发〔2015〕6号](file_2015_6.pdf)