
name: Render and Deploy Quarto Site

on:
  push:
    branches:
      - main

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.17

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: "."

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - name: Install CloudBase CLI
        run: npm install -g @cloudbase/cli
      - name: Enable CloudBase Hosting (if not already enabled)
        run: tcb hosting enable || true

      - name: Deploy to Tencent CloudBase
        working-directory: ./_site
        shell: bash
        run: |
          tcb login --apiKeyId ${{ secrets.secretId }} --apiKey ${{secrets.secretKey}}
          tcb hosting deploy ./ -e ${{secrets.envId}}
