
name: Render and Deploy Quarto Site

on:
  push:
    branches:
      - main

jobs:
  quarto-render-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Quarto
        uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: 1.7.17

      - name: Render Quarto Project
        uses: quarto-dev/quarto-actions/render@v2
        with:
          path: "."

      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/main'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./_site

      - name: upload files to OSS
        uses: fangbinwei/aliyun-oss-website-action@v1
        with:
            accessKeyId: ${{ secrets.ACCESS_KEY_ID }}
            accessKeySecret: ${{ secrets.ACCESS_KEY_SECRET }}
            bucket: "chenq-site"
            endpoint: "oss-cn-shanghai.aliyuncs.com"
            folder: "_site"
